### ISSUE TITLE
kustomizations not entirely idiomatic

### ISSUE THREAD

**Issue by suskin** [crossplane/stack-minimal-gcp#20]
I was pointing my kustomize at the source kustomization for minimal gcp, and got this error:

```
rawResources failed to read Resources: Load from path gcp failed: 'gcp' must be a file
```

I investigated a bit more and learned that kustomize expects directories to be under `bases`, and for all of the entries under `resources` to be individual files (see [this reference](https://kubectl.docs.kubernetes.io/pages/examples/kustomize.html)).

It seems that we'll want to use `bases` for the directories and `resources` only for the individual files.

**Comment by muvaf** [comment]
Actually `bases` field [has been deprecated](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/fields.md#bases) in favor of `resources` to be used for all files and directories. I think the document you linked is not updated.

**Comment by suskin** [comment]
Ahh excellent. Thanks @muvaf !
